-- 01_setup.sf.sql
-- Creates the database, warehouse, and all schemas.
-- Runs first (alphanumeric order) after the LocalStack Snowflake emulator is ready.

CREATE DATABASE IF NOT EXISTS BETTING;

CREATE WAREHOUSE IF NOT EXISTS TRANSFORM
    WAREHOUSE_SIZE = 'XSMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;

USE DATABASE BETTING;

CREATE SCHEMA IF NOT EXISTS RAW;
CREATE SCHEMA IF NOT EXISTS STANDARDISED;
CREATE SCHEMA IF NOT EXISTS CONFORMED;
CREATE SCHEMA IF NOT EXISTS MART;
